# Generated by Django 5.0.1 on 2024-02-19 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_userattempt_date_taken_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ManyToManyField(related_name='employees', to='quiz.department'),
        ),
    ]
